server:
  port: 8082

spring:

  datasource:
    url: jdbc:mysql://mysql:3306/devopsdb
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  redis:
    host: redis
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: DevOpsLearningProjectSecretKey12345678901234567890
  expiration: 86400000

auth-service:
  url: http://auth-service:8081
