apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: devops-project
  labels:
    app: auth-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auth-service

  template:

    metadata:
      labels:
        app: auth-service

    spec:

      containers:

      - name: auth-service

        image: YOUR_DOCKERHUB_USERNAME/auth-service:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 8081

        env:

        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_HOST

        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_PORT

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE

        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_USERNAME

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_PASSWORD

        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST

        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET

        resources:

          requests:
            cpu: "250m"
            memory: "512Mi"

          limits:
            cpu: "500m"
            memory: "1Gi"

        readinessProbe:

          httpGet:
            path: /actuator/health
            port: 8081

          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5

        livenessProbe:

          httpGet:
            path: /actuator/health
            port: 8081

          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
