apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: devops-project

data:

  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: devopsdb

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  AUTH_SERVICE_URL: http://auth-service:8081

  BACKEND_SERVICE_URL: http://backend-service:8082

  JWT_EXPIRATION: "86400000"
