apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: devops-project

type: Opaque

stringData:

  MYSQL_USERNAME: root

  MYSQL_PASSWORD: root123

  JWT_SECRET: DevOpsLearningProjectSecretKey12345678901234567890
